require('plugins._packer')
require('plugins._compe')
require('plugins._autopairs')
require('plugins._formatter')
require('plugins._telescope')
require('plugins._treesitter')
require('plugins._bufferline')
require('plugins.git')
